### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by ZeroLP** [InjectionDev/LeagueSharp#5]
Hi, after seeing your github i would like to contact you for a new platform project.

**Comment by InjectionDev** [comment]
Hi mate, how can i help you ?

Em ter, 8 de jan de 2019 às 12:11, Zero <notifications@github.com> escreveu:

**Comment by ZeroLP** [comment]
I am currently planning to start a new league of legends scripting platform and on a process of developers look out.
for the information, ive made a thread on a forum https://www.nulled.to/topic/631617-wanted-skilled-reverse-game-engineers-and-c-devs/

Also is there a way to contact you other than this way?

**Comment by InjectionDev** [comment]
Sorry mate,

Im afraid that i dont have enough free time atm to start a project like
this from scratch.

Em ter, 8 de jan de 2019 às 19:10, Zero <notifications@github.com> escreveu:

**Comment by ZeroLP** [comment]
This project isnt scratch,  we are intergrating EloBuddy so there is no time consuming.
We really need your skils and talent for this project especially person like you.
We arent offering this for free, if you want we are willing to pay.
Thanks very much.

**Comment by InjectionDev** [comment]
Right, and whats your idea about this project and how could i help you ?

Em sex, 11 de jan de 2019 às 13:49, Zero <notifications@github.com>
escreveu:

**Comment by ZeroLP** [comment]
This project is currently under the way of intergrating EB right now and for the background of this project is to revive the scripting community and replace platforms that arent meeting the users expectation and expensive as hell.
I wanted you in the project because you have previously worked on leaguesharp and also a great candidate for reverse engineer we are looking for. We need your assist to help us reverse engineer the league client and get advices on undection for the loader.

**Comment by ZeroLP** [comment]
Hi, to give you an update; we are currently working on internal project and desperately in need of RE for our internal project.

**Comment by InjectionDev** [comment]
Hey mate!

Im interested to join the team...
I need some time get myself updated about league, cause i I have not worked
with lol for some time.

How can we start ?

Em qua, 13 de mar de 2019 às 00:37, Zero <notifications@github.com>
escreveu:

**Comment by ZeroLP** [comment]
I would like to contact you on Discord or skype preferably

**Comment by ZeroLP** [comment]
+ xSalice is in our team as well :)

**Comment by ZeroLP** [comment]
Most preferably Discord: admiralzero#7647

**Comment by ZeroLP** [comment]
Hey, haven't back from you in a while on Discord. Please let me know on Discord what's going on for you.

**Comment by InjectionDev** [comment]
Hey!

Sorry mate...
I have some work in progress atm that i need to finish before start with
league.

Ill try to help asap, just need some time cause of personal work.


Em seg, 18 de mar de 2019 às 19:20, Zero <notifications@github.com>
escreveu:

**Comment by ZeroLP** [comment]
Sure, what will be the most available ETA for you to start?
